src/content/blog/0030-cmder.yaml

[FIX] Change word

---

src/content/blog/0037-reading_from_redshift.yaml

Creating a PR with a few minor fixes! Some are grammatical fixes, some are slightly more opinionated phrasing changes which seem to make more sense to me but feel free to only take the ones that make sense to you!

[FIX] English review of redshift article

---

package.json
src/content/about/-index.md
src/content/homepage/-index.md
src/layouts/components/Parallax.astro
src/layouts/partials/Header.astro
src/pages/about.astro
src/pages/index.astro

* New `about` page with migrated content from `home`
* Some improvements on `Header` and `Parallax`, mostly about sizing

Astro migration: About page

---

package.json
src/styles/base.scss
src/styles/components.scss
src/styles/utilities.scss

* Problems with `code` and `pre` styling

[FV-83] fix: Code style

---

package.json
src/layouts/Base.astro

[FV-89] Add google analytics

---

package.json
src/layouts/PostSingle.astro

Allow supporters to [Buy me a Coffee](https://www.buymeacoffee.com/villoro)

[FV-94] feat: Add buy me a coffee

---

package.json
src/content/blog/0012-tables_format.mdx
src/content/blog/0018-logging.mdx
src/content/blog/0019-numba.mdx
src/content/blog/0024-pandas_intro.mdx
src/content/blog/0025-pyspark_intro.mdx
src/content/blog/0026-h2o_automl.mdx
src/content/blog/0027-databricks.mdx
src/content/blog/0028-pyspark_example.mdx
src/content/blog/0030-cmder.mdx
src/content/blog/0034-pyspark_java_udf.mdx
src/content/blog/0036-regex.mdx
src/content/blog/0038-poetry_versioning.mdx
src/styles/components.scss

* Improve `tables` styles
* Remove old `html` tables for `markdown` ones since they are easier to read and they produce the same output

[FV-91] Improve tables style

---

package.json
src/layouts/PostSingle.astro

* Add [giscus.app](https://giscus.app/) for comments

[FV-78] Add giscus

---

package.json
src/content/blog/0039-rewrite-git-history.mdx

[FV-106] Rewrite git history

---

.github/scripts/check_if_update_needed.py
.github/workflows/check_version.yaml
package.json

* Forces the version to be different from `main`

[NO-ISSUE] fix: CI job to fix version

---

package.json
src/content/blog/0044-running-dbt.mdx
src/content/blog/0046-salesforce.mdx

* Release DBT post
* Add section in salesforce about data size

[FV-102] release: DBT post

---

package.json
src/layouts/components/BlogTags.astro
src/lib/blogUtils.astro
src/pages/blog/index.astro
src/pages/blog/page/[slug].astro
src/pages/tags/[tag].astro
src/pages/tags/[tag]/page/[slug].astro

* Add `tags` pagination
* Simplify posts grid
* Improve `BlogTags` accesibility

[FV-96] Tags pagination

---

package.json
src/config/config.json
src/layouts/PostSingle.astro
src/layouts/components/BlogDetails.astro
src/layouts/components/TOC.astro
src/styles/components.scss

* Add lateral TOC on big screens
* Replace emoji for dates (`FaRegCalendar`)

[FB-87] Add lateral TOC on big screens

---

astro.config.mjs
package.json
src/layouts/PostSingle.astro
src/styles/components.scss

* Highlight sections that are visible in the TOC

[FV-87] TOC highlights

---

package.json
src/layouts/components/CategoryDisplay.astro
src/lib/utils/taxonomyFilter.ts
src/pages/blog/index.astro
src/pages/blog/page/[slug].astro
src/pages/categories/[category].astro
src/pages/categories/[category]/page/[slug].astro
src/pages/tags/[tag].astro
src/pages/tags/[tag]/page/[slug].astro

Add titles to all pages that have a blog grid

[NO-ISSUE] Show titles in all blog grids

---

package.json
src/content/blog/0040-prefect-essentials.mdx

Describe how to cancel prefect flow runs

[NO-ISSUE] Improve prefect post

---

package.json
src/content/blog/0040-prefect-essentials.mdx

Minor improvements in prefect essentials post

[NO-ISSUE] Minor fixes prefect post

---

package.json
src/content/blog/0047-install_windows.mdx

* Release `clean windows install` post

[FV-131] Release windows post

---

package.json
src/content/blog/0052-open-ai-async.mdx

[DI-178] Post Async open ai

---

package.json
src/content/blog/0048-calls-open-ai.mdx
src/content/blog/0051-dbt-failures.mdx

[FV-130] Release whisper post

---

package.json
src/content/blog/0052-open-ai-async.mdx

[DI-178] Release async open ai post

---

package.json
src/content/blog/0049-open-ai-async.mdx

[NO-ISSUE] Fix some links

---

package.json
src/content/blog/0047-install_windows.mdx

Improve windows installation instructions

[NO-ISSUE] Improve windows instructions
